// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsohejnldwvwfjyrscxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhzb2hlam5sZHd2d2ZqeXJzY3hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDU0NDQsImV4cCI6MjA2MTIyMTQ0NH0.u-f8z3iy_ZR09HtEo3ZEsD22pGIR9yOFS1GTTbTOrVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);